[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    "forge-std=lib/forge-std/src",
    "solidity-rlp=lib/solidity-rlp/contracts",
    "@eth-optimism/contracts-bedrock=lib/optimism/packages/contracts-bedrock/src"
]

fs_permissions = [{ access = "read-write", path = "./" }]

solc_version = "0.8.19"
optimizer = true
optimizer_runs = 1000000
